// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHjCABkBqAJ_jH-6c2RVQbG1EESR3s0o',
    appId: '1:884729725072:web:9bee87c4d5366f15881815',
    messagingSenderId: '884729725072',
    projectId: 'mynotes2-flutter-zaki',
    authDomain: 'mynotes2-flutter-zaki.firebaseapp.com',
    storageBucket: 'mynotes2-flutter-zaki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3sHEqoN_F9-nSnKafBE0ZNI3RncmqC98',
    appId: '1:884729725072:android:ce743c452cfdd130881815',
    messagingSenderId: '884729725072',
    projectId: 'mynotes2-flutter-zaki',
    storageBucket: 'mynotes2-flutter-zaki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmTbzuA4ga6Mrfm0sIlG4Q-ag1f92nsU',
    appId: '1:884729725072:ios:923d84a11ea3aaaf881815',
    messagingSenderId: '884729725072',
    projectId: 'mynotes2-flutter-zaki',
    storageBucket: 'mynotes2-flutter-zaki.appspot.com',
    iosClientId: '884729725072-8mangs8t6vjeri4ebn0psdr6e07s0gf0.apps.googleusercontent.com',
    iosBundleId: 'my.zaki.mynotes2',
  );
}
